aliases:
  - &restore-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      # Fallback in case checksum fails
      - dependencies-
  #- &restore-cache-example
  #  keys:
  #    - dependencies-{{ checksum "example/package.json" }}
  #    # Fallback in case checksum fails
  #    - dependencies-

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ checksum "package.json" }}
  #- &save-cache-example
  #  paths:
  #    - example/node_modules
  #  key: dependencies-{{ checksum "example/package.json" }}

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn install
      - save-cache: *save-cache
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn test -- --coverage -i
      - store_artifacts:
          path: coverage
